module serpent:
    snakefile: "/home/jb/development/serpent/workflow/Snakefile"

OUTDIR = config["act"]["outdir"]["process_vcf"]
M_VCF_OUT_PFX = f"{OUTDIR}/results/vcf/chr{{chromosome}}_filtered.vcf.gz"
rule all:
    input:
        vcf=expand(M_VCF_OUT_PFX, chromosome=config["CHROMOSOMES"]),
        tbi=expand(f"{M_VCF_OUT_PFX}.tbi", chromosome=config["CHROMOSOMES"]),

CREATE_EXCL_OUT = f"{OUTDIR}/temp/{{cohort}}/var_excl_lists/chr{{chromosome}}_excl.txt"
use rule create_variant_exclude_delim from serpent as serpent_create_variant_exclude_delim with:
    container: config["images"]["vcftools"]
    input: "/container/act/{cohort}/TOPMEDr2/infofile/chr{chromosome}.info.gz"
    output: temp(CREATE_EXCL_OUT)
    log: f"{OUTDIR}/logs/create_variant_exclude_delim/{{cohort}}/chr{{chromosome}}.log"
    params:
        avg_call=config["vcf"]["avg_call"],
        rsq_common=config["vcf"]["rsq_common"],
        maf_thresh=config["vcf"]["maf_thresh"],
        rsq_rare=config["vcf"]["rsq_rare"]

F_VCF_IN_PFX = "/container/act/{cohort}/TOPMEDr2/vcffile/chr{chromosome}.dose.vcf.gz"
F_VCF_OUT_PFX = f"{OUTDIR}/temp/{{cohort}}/filtered_vcfs/chr{{chromosome}}_filtered.vcf.gz"
use rule filter_vcf from serpent as serpent_filter_vcf with:
    container: config["images"]["bcftools"]
    input:
        vcf=F_VCF_IN_PFX,
        tbi=F_VCF_IN_PFX + ".tbi",
        exclude=CREATE_EXCL_OUT,
    output:
        vcf=temp(F_VCF_OUT_PFX),
        tbi=temp(F_VCF_OUT_PFX + ".tbi"),
    log: f"{OUTDIR}/logs/filter_vcf/{{cohort}}/chr{{chromosome}}.log"

use rule merge_vcf from serpent as serpent_merge_vcf with:
    container: config["images"]["bcftools"]
    input:
        vcf=expand(F_VCF_OUT_PFX, cohort=config["bfiles"].keys(), allow_missing=True),
        tbi=expand(F_VCF_OUT_PFX + ".tbi", cohort=config["bfiles"].keys(), allow_missing=True),
    output:
        vcf=M_VCF_OUT_PFX,
        tbi=M_VCF_OUT_PFX + ".tbi",
    log: f"{OUTDIR}/logs/merge_vcf/chr{{chromosome}}.log"
