module serpent:
    #snakefile: github("broomej/serpent", path="workflow/Snakefile", tag=config.get("serpent_version"))
    snakefile: github("broomej/serpent", path="workflow/Snakefile", commit="1fbad34925a23e2efeb8123dad1af20c28b00f35")

ROOTDIR = config["project_root"]["act"]
PROJNAME = config["act_dir"]["data_prep"]
PROJDIR = f"{ROOTDIR}/{PROJNAME}"
RESDIR = f"{PROJDIR}/results"
LOGDIR = f"{PROJDIR}/logs"
TEMPDIR = f"{PROJDIR}/temp"

CREATE_EXCL_OUT=f"{TEMPDIR}/{{cohort}}/var_excl_lists/chr{{chromosome}}_excl.txt"
use rule create_variant_exclude_delim from serpent as serpent_create_variant_exclude_delim with:
    container: VCFTOOLS_IMG
    input: f"{ACT_DATA_DIR}/{{cohort}}/TOPMEDr2/infofile/chr{{chromosome}}.info.gz"
    output: temp(CREATE_EXCL_OUT)
    log: f"{LOGDIR}/create_variant_exclude_delim/{{cohort}}/chr{{chromosome}}.log"
    params:
        avg_call=config["avg_call"],
        rsq_common=config["rsq_common"],
        maf_thresh=config["maf_thresh"],
        rsq_rare=config["rsq_rare"],

F_VCF_IN_PFX = f"{ACT_DATA_DIR}/{{cohort}}/TOPMEDr2/vcffile/chr{{chromosome}}.dose.vcf.gz"
F_VCF_OUT_PFX = f"{TEMPDIR}/{{cohort}}/filtered_vcfs/chr{{chromosome}}_filtered.vcf.gz"
use rule filter_vcf from serpent as serpent_filter_vcf with:
    container: BCFTOOLS_IMG
    input:
        vcf=F_VCF_IN_PFX,
        tbi=F_VCF_IN_PFX + ".tbi",
        exclude=CREATE_EXCL_OUT,
    output:
        vcf=temp(F_VCF_OUT_PFX),
        tbi=temp(F_VCF_OUT_PFX + ".tbi"),
    log: f"{LOGDIR}/filter_vcf/{{cohort}}/chr{{chromosome}}.log"

M_VCF_OUT_PFX = f"{RESDIR}/vcf/chr{{chromosome}}_filtered.vcf.gz"
use rule merge_vcf from serpent as serpent_merge_vcf with:
    container: BCFTOOLS_IMG
    input:
        vcf=expand(F_VCF_OUT_PFX, cohort=COHORTS, allow_missing=True),
        tbi=expand(F_VCF_OUT_PFX + ".tbi", cohort=COHORTS, allow_missing=True),
    output:
        vcf=M_VCF_OUT_PFX,
        tbi=M_VCF_OUT_PFX + ".tbi",
    log: f"{LOGDIR}/merge_vcf/chr{{chromosome}}.log"
